DROP TABLE IF EXISTS APPLICANT;

CREATE TABLE APPLICANT (
           id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
           name VARCHAR(250) NOT NULL,
           email VARCHAR(250) NOT NULL,
           repository_url VARCHAR(250) DEFAULT NULL
);