<!DOCTYPE html>
<html>
<head>
    <title> ${name} - Teszt Feladat</title>
</head>
<body>
    <h1>Teszt Feladat</h1>
    <p><a href="${repositoryUrl}">Megoldás</a></p>
    <p>A feladat elkészítőjének adatai</p>
    <table border="1px solid black">
        <tr>
            <td>Név</td>
            <td>${name}</td>
        </tr>
        <tr>
            <td>Elérhetőség</td>
            <td>${email}</td>
        </tr>
    </table>
    <a href="http://lpsolutions.hu">L&P Solutions</a>
</body>
</html>